# Generated by Django 3.0.5 on 2020-04-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quali', models.TextField()),
                ('duty', models.TextField()),
                ('category', models.IntegerField()),
            ],
        ),
    ]
